### ISSUE TITLE
Make error on Arch

### ISSUE THREAD

**Issue by WaltzNightray** [onitake/gslx680-acpi#38]
Hello onitake,

Is this driver still being maintained?

If so, I'd like to verify if there's any fix for the following issue: I received a make error when building the root file (this is for use with Silead firmware, for the MW11 Multilaser touchscreen):

`[root@multilaser gslx680-acpi-master]# make
make -C /lib/modules/6.5.7-arch1-1/build ARCH=x86_64 CROSS_COMPILE= M=/home/multi/Downloads/gslx680-acpi-master modules
make[1]: Entering directory '/usr/lib/modules/6.5.7-arch1-1/build'
  CC [M]  /home/multi/Downloads/gslx680-acpi-master/gslx680_ts_acpi.o
/home/multi/Downloads/gslx680-acpi-master/gslx680_ts_acpi.c:760:18: error: initialization of ‘int (*)(struct i2c_client *)’ from incompatible pointer type ‘int (*)(struct i2c_client *, const struct i2c_device_id *)’ [-Werror=incompatible-pointer-types]
  760 |         .probe = gsl_ts_probe,
      |                  ^~~~~~~~~~~~
/home/multi/Downloads/gslx680-acpi-master/gslx680_ts_acpi.c:760:18: note: (near initialization for ‘gslx680_ts_driver.<anonymous>.probe’)
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: /home/multi/Downloads/gslx680-acpi-master/gslx680_ts_acpi.o] Error 1
make[2]: *** [/usr/lib/modules/6.5.7-arch1-1/build/Makefile:2034: /home/multi/Downloads/gslx680-acpi-master] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.5.7-arch1-1/build'
make: *** [Makefile:18: modules] Error 2
`

I thank you in advance for any help on this.

**Comment by onitake** [comment]
Sorry, this driver is completely unmaintained. I should probably add a banner to the readme to make this clear.
Please use the mainline silead.ko driver instead.

That being said, this error is caused by a change in the kernel I²C driver API. The probe function signature changed from kernel 6.2 to 6.3, and it no longer has the second parameter.
6.2: https://elixir.bootlin.com/linux/v6.2.16/source/include/linux/i2c.h#L276
6.3: https://elixir.bootlin.com/linux/v6.3/source/include/linux/i2c.h#L277

If you'd like submit a patch that makes it work with 6.3+, I'd be happy to accept it. Please do take care that compatibility with older kernels isn't broken, so you should add suitable `#if LINUX_VERSION_CODE >= KERNEL_VERSION(6,3,0)` lines.
